services:
  backend:
    build:
      context: ./backend
    image: leafnoise-backend:latest
    container_name: flask-backend
    ports:
      - "8000"
    networks:
      - leafnoise-net

  frontend:
    build:
      context: ./frontend
    image: leafnoise-frontend:latest
    container_name: nginx-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - leafnoise-net

networks:
  leafnoise-net:
    driver: bridge
